### ISSUE TITLE
Bug: 关键词为中文时关键词被过滤掉了

### ISSUE THREAD

**Issue by yi03** [koishijs/novelai-bot#119]
### Describe the bug

我加载了很多别人生成好的 Textual Inversion embeddings ，有些 embedding 的关键词是中文，输入的时候被过滤掉了。关键词为英文的 embedding 则正常。

### Steps to reproduce

[embeddings.zip](https://github.com/koishijs/novelai-bot/files/10047142/embeddings.zip)
这是五个embedding文件，op-ganyu、op-naxida关键词为英文，申鹤、雏鹤爱、霞泽美游的关键词为中文。

首先我关闭了自动翻译和只接受英文输入。卸载了所有翻译插件。
![](https://user-images.githubusercontent.com/32034998/202854810-66059e74-d57c-4cdc-9470-5618f4fbfad9.png)
违禁词列表只有nude, naked。

直接使用webui时输入`申鹤`这个关键词AI是认识的：
![](https://user-images.githubusercontent.com/32034998/202854905-95202a47-4a4d-462d-8385-6fd436d7b551.png)
但是使用bot时，给出的却是不相干的人物。使用png info查看后发现`申鹤`这个关键词就没有输入进去：
![](https://user-images.githubusercontent.com/32034998/202855207-7cee1c53-99c6-403b-8b9f-466904f18e96.png)

### Expected behavior

如果使用英文关键词`op-ganyu`的话，能正常显示人物图片，并且png info里也有输入的英文关键词：
![](https://user-images.githubusercontent.com/32034998/202855422-99e877df-ae47-43bc-9ccf-48538de994a8.jpg)

### Launcher

Koishi CLI (koishi start)

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: Windows 11
- Adapter: onebot
- Node version: 16.18.0
- Koishi version: 4.10.2

**Comment by MaikoTan** [comment]
Confirmed.

https://github.com/koishijs/novelai-bot/blob/1bdfbc9389b483c0a85ae79f8f18d46ec204db0e/src/config.ts#L279-L291

It is caused by line 281 which replaces words with a space except for English characters and digits.
This code was originally used to filter forbidden words without being influenced by emphasis brackets.
So is there a solution to capture those without changing much?

**Comment by shigma** [comment]
已于 1.14.3 版本修复此问题。
