### ISSUE TITLE
Feature: 请求支持lantent放大算法

### ISSUE THREAD

**Issue by SurviveZ** [koishijs/novelai-bot#173]
### Scope

Stable Diffusion WebUI (AUTOMATIC1111)

### Describe the problem related to the feature request

部分模型要求使用Lantent放大算法来达到最佳效果

### Describe the solution you'd like

在配置中可选择Lantent放大算法

### Describe alternatives you've considered

无

### Additional context

无

**Comment by MaikoTan** [comment]
Hello, @SurviveZ 

Merci for the issue!

I do a quick search for latent upscale and found there are several PR for this: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/5521 https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6299 https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6364

So it looks like that you could only use the latent upscaler with `img2img` and `hires fix` features? Could you explain to me how it works and which approach this feature is implemented you like?

------

你好 @SurviveZ 

多谢你的议题！

我做了一个对于潜在的高档快速检索，然后找到了几个 PR：
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/5521 https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6299 https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6364

所以看起来你只能使用具有 `img2img` 和 `hires fix` 功能的潜在升频器？您能向我解释一下它是如何工作的，以及您喜欢哪种实现此功能的方法吗？

**Comment by SurviveZ** [comment]
> 

你好，使用其他放大算法最终无法正常生成并发送图片，在webui上使用lantent则能够较快生成，这是主要原因.

**Comment by MaikoTan** [comment]
> 你好，使用其他放大算法最终无法正常生成并发送图片，在webui上使用lantent则能够较快生成，这是主要原因.

I think that's because you have [`requestTimeout`](https://bot.novelai.dev/config.html#requesttimeout) set with a small number (like the default value 60 seconds is too small for many consumer-level spec when generating large images), so maybe it works with a longer timeout like 2min or 5min or whatever.

我认为那是因为你 [`requestTimeout`](https://bot.novelai.dev/config.html#requesttimeout) 设置了一个小数字（比如默认值 60 秒对于许多消费级规范来说太小了，当生成大图像），所以也许它可以使用更长的超时时间，如 2 分钟或 5 分钟或其他任何时间。

------

Thanks for the reply.
What I am asking is that whether the latent upscaler usable in `upscale` (or `Extra` in sd-webui) or not. Or should I make it only usable for `hires fix` and `img2img`?

谢谢你的回复。
我想问的其实是潜在升档器是否在`高档` (或 sd-webui 中的 `额外`) 中可用。亦或我应该让它仅能用于`高分辨率修复`和`img2img`吗？

**Comment by SurviveZ** [comment]
> ![image](https://user-images.githubusercontent.com/91445888/218399036-2f3f9174-0563-4081-8e85-f1016649485a.png)
> 
> 我想它可能是需要在配置项中添加lantent放大算法（这在webui中的upscale是可用的，并且它会影响图片效果），由于sd-webui的api中的get方法没有lantent，你可能需要手动添加它或者等待sd-webui更新，这是临时解决方法：
> 
> ![image](https://user-images.githubusercontent.com/91445888/218399503-7bcc4cef-b683-4b5a-90b0-b5e08dd30937.png)
> 
> latent=['Latent','Latent (antialiased)','Latent (bicubic)','Latent (bicubic antialiased)','Latent (nearest)','Latent (nearest-exact)'] 请注意它们含有空格。

请问这是在哪里修改呢？
