### ISSUE TITLE
Bug: 反馈一个条件限制无效的BUG

### ISSUE THREAD

**Issue by waterminer** [koishijs/novelai-bot#183]
### Describe the bug

加入条件限制后，并不能有效限制用户

### Steps to reproduce

在更新版本后，加入了一个能按照条件限制指令的功能

我给maxResolution加入了一个条件：

| 条件 | 参数 |
| --- | --- |
| 当满足条件：用户ID=[我的QQ账号] | 1280 |
| 其他情况下：| 1024 |

### Expected behavior

我期望它只会对我开放使用超过 1024分辨率大小的图像（比如1280）并且限制其他人不能生成超过1024分辨率的图像
但是，目前而言，哪怕我添加了这个设置其他所有人仍然能使用该机器人生成超过 1024 分辨率的图像

### Screenshots

![设置参数](https://tupian.li/images/2023/03/10/640b050c0bb80.jpg "设置参数")
设置参数

![image](https://tupian.li/images/2023/03/10/640b050c49c40.jpg)
图中，蓝色对话框的是我自己（期望限制最大大小为1280的用户）
白色对话框是其他人（希望限制大小为1024的用户）

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: Windows 10 
- Adapter: OneBot
- Node version: 18.12.1
- Koishi version: 4.11.9
- plugin version: 1.17.3

**Comment by MaikoTan** [comment]
这是预期的，不是 Bug。

您应当使用`属于`或`不属于`对于一个用户ID/群组ID/频道ID，而不是`等于`或`不等于`。
虽然您使用的用户IDs是数字的，但这个事实并不总是对的在一些平台。这是为何我们把用户IDs当作字符串而不是数字。所以为了比较一个字符串，您使用的`等于`并不适合这个盒子。

<details><summary>The original text</summary>

It is expected, not a bug.

You should use `Include` or `Exclude` for a UserID/GroupID/ChannelID, not `Equal` or `Not Equal`.
While the UserID you're using is numeric, but the fact is not true on some platform. That's why we treat the UserIDs as a string rather than number. So in order to compare a string, the `Equal` You're using is not suitable in this case.

</details>
