### ISSUE TITLE
Bug: Stable Horde下电脑QQ无法显示图片

### ISSUE THREAD

**Issue by deedlitelf** [koishijs/novelai-bot#190]
### Describe the bug

手机QQ正常显示图片，电脑QQ上图片要么显示裂开要么就是一直待加载，从历史记录的CQ码的图片url中可以正常读取图片。看了一下代码似乎是Stable Horde默认返回webp造成的，但是将格式更改后无效。

### Steps to reproduce

koishi挂载环境：Windows server 2012R
电脑端绘图

### Expected behavior

电脑可以正常显示图片（将图片发送前先转为jpg或png格式？）

### Screenshots

![(~_E852FRRXVTXRXZBLJ5`9](https://user-images.githubusercontent.com/47165683/228293530-d4b59d07-b58a-4e9c-92a6-404e1f774dd3.png)
CQ码图片：https://gchat.qpic.cn/gchatpic_new/1400485038/776771034-2213352280-03E0AA8952DA123DB5E61E98038B6E9C/0?term=2&is_origin=0

### Launcher

Koishi Desktop

### Backend

Stable Horde

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version:

**Comment by MaikoTan** [comment]
This is an upstream bug of Tencent QQ, not the plugin itself.
That is because the image format that the plugin sent from Stable Horde is [`WebP`](https://en.wikipedia.org/wiki/WebP) rather than PNG or JPEG or something. And Windows PCQQ seems lacking of WebP support but Mac OS QQ and Mobile QQ support it. So I am assuming this could not be fixed by our side.

On the other hand, if you are using [`Mrs4s's go-cqhttp`](https://github.com/Mrs4s/go-cqhttp) as your QQ adapter backend, `go-cqhttp` introduced [a new feature](https://github.com/Mrs4s/go-cqhttp/blob/82ecf19480368d02496168f8c397b0c96b87c0c0/modules/config/default_config.yml#L48) that it could convert webp to png before sending your messages. Open your `go-cqhttp` config file and just change the `convert-webp-image: false` line to `convert-webp-image: true`, then reboot your `go-cqhttp`.

**Comment by deedlitelf** [comment]
Thanks
