### ISSUE TITLE
希望可以增加对_\和l\的支持

### ISSUE THREAD

**Issue by Gelmezon** [koishijs/novelai-bot#65]
是否可以增加对_\和l\的支持 是描述背景用的 效果不错
ps 如果可以指定一个更好的分辨率就更好了 (比如1024x1024

![微信图片_20221021120246](https://user-images.githubusercontent.com/20065068/197108990-1645f168-d678-4d3e-b18f-6717d40d2449.jpg)
![微信图片_20221021120252](https://user-images.githubusercontent.com/20065068/197108995-fa91071b-d2b0-415f-a363-898fe4d86800.jpg)

**Comment by Gelmezon** [comment]
约稿 -c 15 ,best quality, masterpiece, ultra-detailed, illustration, detailed light, an extremely delicate and beautiful, beautiful detailed eyes, stars in the eyesfrom above, long_hair,jewelry,navel, see-through, earrings, very_long_hair, looking_at_viewer, blonde_hair,star_hair_ornament,long_hair, planet, solo, star_necklace,earrings,dancer, blonde_hair,open_mouth,long_hair, solo, dress, sparkle_background, bangs,  cape, very_long_hair, gloves, star_\(sky\), shooting_star, 1girl, starry_sky, glint, star_\(symbol\), diffraction_spikes, constellation, sky, finely detailed background,starfish, maple_leaf, autumn_leaves, starry_background, leaf,saint_quartz_\(fate\), falling_leaves, space, night_sky, starry_sky_print, sky, star_pasties, night,moon,yellow_butterfly, lake, star_print,jewelry, snowing, planet,galaxy, sky, light_particles, fireworks, earth_\(planet\), star_\(symbol\)

**Comment by MaikoTan** [comment]
In most cases you don't need `_` in your prompt, just use a space.
But supporting the `\` or `\(` `\)` should be in the roadmap, [since we are going to support sd-webui](#64) which using `()` instead of `{}`.

在大多数情况下，你不需要在提示符中使用`_`，只需使用空格。
但是支持`\`或`\(` `\)`应该在路线图中，因为我们[将支持使用`()`而不是`{}`的sd-webui](#64)。

**Comment by MaikoTan** [comment]
BTW, according to [novelai](https://novelai.net/), when you have a subscription of Enthusiast tier, you can freely generate images under 640*640 and 28 steps. If you specified a pair of larger width and height, your "Anlas" point would be cost. So that's why we didn't provide a wider option for tweaking the image size. 

BTW，根据[novelai](https://novelai.net/)，当你有一个爱好者级别的订阅，你可以自由生成640*640和28步以下的图像。如果你指定一对更大的宽度和高度，你的 "Anlas" 点将会是成本。所以这就是为什么我们没有提供一个更广泛的选项来调整图像的大小。

**Comment by shigma** [comment]
@Gelmezon 感谢你的建议！

1.11.2 版本支持了新的 `-v, --viewport` 参数，除了允许过去的 portrait, landscape 和 square 外，还支持 `1024x1024` 这样的语法。

**Comment by shigma** [comment]
1.11.3 版本已经支持转义字符和 `(){}` 自动转换。目前的逻辑：

- 全角圆括号和冒号 `（）：` 会被首先替换为半角字符 `():`
- 连续的 `\\` 视为单个的 `\` 而非转义字符
- 如果 `(){}` 出现在转义字符后，则不做任何处理
- 如果 `(){}` 未出现在转义字符后，则根据后端的类型：
  - 如果是 sd-webui，则统一转换为 `()`
  - 否则统一转换为 `{}`
